[project]
name = "fosquesttools"
version = "0.1.0"
description = "Tools for processing Fosquest assets"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "mido>=1.3.3",
]
