[project]
name = "midi2snd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "mido>=1.3.3",
]

[project.scripts]
parse='main:parse'
