
%ifndef INPUT_MAC_ASM
%define INPUT_MAC_ASM

%define KEYCODE_NONE 0x00
%define KEYCODE_ESC 0x01
%define KEYCODE_ENTER 0x1c
%define KEYCHAR_BACKSPACE 0x08
%define KEYCODE_UP 0x48
%define KEYCODE_LEFT 0x4b
%define KEYCODE_RIGHT 0x4d
%define KEYCODE_DOWN 0x50

%endif ; INPUT_MAC_ASM